### ISSUE TITLE
question about the code

### ISSUE THREAD

**Issue by wlnancy** [ashar207/Federated-Learning#1]
Hi, I want to use another dataset, how should I process the dataset?

**Comment by an4nt** [comment]
Hi, which dataset do you want use? You can define a new loader function to process that dataset similar to ones in dataset.py

**Comment by wlnancy** [comment]
I want to use cifar10. And I define a new loader function in dataset.py. But it occurs some errors because this dataset  is not a grayscale and it use 3 channels. I don't know how to change the code.

**Comment by an4nt** [comment]
I think you can transform the dataset into grayscale by modifyinng the transform compose like this,
```
transform = transforms.Compose([tv.transforms.Grayscale(num_output_channels=1),
                                    tv.transforms.ToTensor()])
```
Or you can modify the model to accept multiple image channels by changing the input of conv1 layer in model.py to this,
```
self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1, stride=1)
```

**Comment by wlnancy** [comment]
Thanks for your suggestions, and I modify the model by changing the input of conv1 layer as you said. But it occurs the error :
Traceback (most recent call last):
&nbsp; File "F:/python/FederatedLearningtest/train_federatedcompDuchi.py", line 277, in <module&gt;
&nbsp; &nbsp; param, loss = train(copy.deepcopy(global_model), DEVICE, train_distributed_dataset[idx], LOCAL_ITERS)
&nbsp; File "F:/python/FederatedLearningtest/train_federatedcompDuchi.py", line 96, in train
&nbsp; &nbsp; output = local_model(data)
&nbsp; File "D:\Program Files\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "F:\python\FederatedLearningtest\model.py", line 46, in forward
&nbsp; &nbsp; x = x.view(-1, FLATTEN_SIZE)
RuntimeError: shape '[-1, 3136]' is invalid for input of size 20480

Maybe do you know how to modify the code to solve the problem?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ashar207/Federated-Learning"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 晚上10:19
收件人:&nbsp;"ashar207/Federated-Learning"<Federated-Learning@noreply.github.com&gt;;
抄送:&nbsp;"王蕾"<945389942@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ashar207/Federated-Learning] question about the code (#1)





 
I think you can transform the dataset into grayscale by modifyinng the transform compose like this,
 transform = transforms.Compose([tv.transforms.Grayscale(num_output_channels=1),                                     tv.transforms.ToTensor()])  
Or you can modify the model to accept multiple image channels by changing the input of conv1 layer in model.py to this,
 self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1, stride=1)

**Comment by an4nt** [comment]
You need to change the FLATTEN_SIZE defined in line 21 of model.py according to the image size of the dataset. The current flatten size is set for (1x28x28) image which comes out be 64*7*7 = 3136, you can calculate the final image size by referring to the comments in model.py file (which I guess should be 20480).
